---
  - hosts: all
    become: true

    tasks:
      - name: STOP APACHE2
        service: name=apache2 state=stopped

      - name: COPY INDEX.HTML FOR SHOW INDEX NGINX
        ansible.builtin.file: path=/var/www/html/index.html state=absent

      - name: COPY INDEX.PHP
        ansible.builtin.copy: src=php/index.php dest=/var/www/html/index.php remote_src=false

      - name: COPY HTACCESS
        ansible.builtin.copy: src=php/.htaccess dest=/var/www/html/.htaccess remote_src=false

      - name: COPY APACHE2_CONF
        ansible.builtin.copy: src=apache2/apache2.conf dest=/etc/apache2/apache2.conf remote_src=false

      - name: START APACHE2
        service: name=apache2 state=started
